// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArjKZkj1uwf7Gu9q1LFGDHVYnmWkmFwH0',
    appId: '1:142157161775:web:27c9f3001232a695eaedda',
    messagingSenderId: '142157161775',
    projectId: 'studdy-buddy-d7db3',
    authDomain: 'studdy-buddy-d7db3.firebaseapp.com',
    storageBucket: 'studdy-buddy-d7db3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFtE4nEOQSOVq5Q1wi0N7GZvcHtJzC7Rc',
    appId: '1:142157161775:android:da0f1e5439f26bbceaedda',
    messagingSenderId: '142157161775',
    projectId: 'studdy-buddy-d7db3',
    storageBucket: 'studdy-buddy-d7db3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOOUNpmgQH5Pq3m2AUYdr4Ul3ihH9rxUk',
    appId: '1:142157161775:ios:81a20881bff862c5eaedda',
    messagingSenderId: '142157161775',
    projectId: 'studdy-buddy-d7db3',
    storageBucket: 'studdy-buddy-d7db3.appspot.com',
    iosClientId: '142157161775-rh9hibbpjhranui1kal3cfvlb56r9tio.apps.googleusercontent.com',
    iosBundleId: 'com.example.studdyBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOOUNpmgQH5Pq3m2AUYdr4Ul3ihH9rxUk',
    appId: '1:142157161775:ios:81a20881bff862c5eaedda',
    messagingSenderId: '142157161775',
    projectId: 'studdy-buddy-d7db3',
    storageBucket: 'studdy-buddy-d7db3.appspot.com',
    iosClientId: '142157161775-rh9hibbpjhranui1kal3cfvlb56r9tio.apps.googleusercontent.com',
    iosBundleId: 'com.example.studdyBuddy',
  );
}
